---
- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: delete kubelet.conf if exists
  file:
    path: "/etc/kubernetes/kubelet.conf"
    state: absent
  when: kubelet_conf.stat.exists

- name: Join to cluster if needed
  include_tasks: join.yml

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes