---
- name: Reset kubernetes cluster
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Init kubernetes cluster
  when: reset_cluster is succeeded
  shell:
    kubeadm init --service-cidr {{ service_cidr }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --token {{ token }} \
                 --apiserver-advertise-address {{ master_ip }}
  register: init_cluster
