---
- name: Check if kubeadm is running
  stat:
    path: "etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Init cluster if needed
  include_tasks: init.yml
  when: not kubeadm_ca.stat.exists
  run_once: yes

- name: Create Kubernetes config dir
  file:
    path: "{{ k8s_user_home }}/.kube"
    state: directory
    owner: "{{ k8s_user_id }}"
    group: "{{ k8s_user_gid }}"

- name: Copy admin.conf to home dir
  copy:
    src: "{{ kubeadmin_config }}"
    dest: "{{ k8s_user_home }}/.kube/config"
    owner: "{{ k8s_user_id }}"
    group: "{{ k8s_user_gid }}"
    mode: 0755
    remote_src: true

- name: Enable and check kubelete service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_kubelet