---
- name: Ensure persistent journal logs are enabled
  file:
    path: /var/log/journal
    state: directory

- name: Uninstall conflict package
  apt:
    name:
      - podman-docker
      - buildah
      - podman
    state: absent

- name: Update repo cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # one day